# Copyright 2023-2024 Amazon.com, Inc. or its affiliates.

name: osml_model_runner_test
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.11
  - conda-forge::gdal=3.7.2
  - conda-forge::proj=9.3.0
