name: "OSML Model Runner Test Build and Publish Workflow"

on:
  push:
    branches: ["main", "dev"]

jobs:
  Build_Validate_Tox:
    uses: ./.github/workflows/python-tox.yml
    secrets: inherit
  Publish_Documentation:
    needs: [Build_Validate_Tox]
    uses: ./.github/workflows/documentation-publish.yml
    secrets: inherit
  Notify_Guidance_Repo:
    needs: [Publish_Documentation]
    uses: ./.github/workflows/notify-guidance-repo.yml
    secrets: inherit